export const FETCH_COLLECTIONS = "FETCH_COLLECTIONS"
export const FETCH_USER_COLLECTIONS = "FETCH_USER_COLLECTIONS"

export const FETCH_ITEMS = "FETCH_ITEMS"
export const FETCH_COLLECTION_ITEMS = "FETCH_COLLECTION_ITEMS"
export const FETCH_TAG_ITEMS = "FETCH_TAG_ITEMS"